Repository yoitsmedarls/CDM-Nexus, pull requests merged in 2025-03, with the labels that each got.

#32 Updated dependencies.
  package-lock.json
Labels: dependencies

#43 Feature/admin route lesson list
  src/routes/courses/[slug]/+page.server.ts
  src/routes/courses/[slug]/+page.svelte
Labels: enhancement

#44 Fixed numerous eslint errors across multiple files.
  src/lib/components/landing-page/Footer.svelte
  src/lib/components/landing-page/Header.svelte
  src/lib/components/landing-page/Join.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/admin/login/+page.svelte
  src/routes/course-list/+layout.svelte
  src/routes/course-list/+page.svelte
  src/routes/course-list/library/+page.server.ts
  src/routes/course-list/library/+page.svelte
  src/routes/courses/+layout.svelte
  src/routes/courses/+page.svelte
  src/routes/courses/[slug]/+page.server.ts
  src/routes/courses/[slug]/+page.svelte
Labels: bug

#46 Cleaned up various routes in preparation for checking.
  src/lib/components/admin/dashboard/Dashboard.svelte
  src/lib/components/admin/dashboard/NavigationBar.svelte
  src/routes/admin/+page.server.ts
  src/routes/admin/dashboard/+page.server.ts
  src/routes/admin/dashboard/+page.svelte
  src/routes/admin/login/+page.server.ts
  src/routes/admin/login/+page.svelte
  src/routes/course-list/+page.svelte
  src/routes/courses/+layout.svelte
  src/routes/courses/[slug]/+page.server.ts
  src/routes/courses/[slug]/+page.svelte
  src/routes/old-admin/dashboard/+page.svelte
Labels: bug, enhancement

#58 Updated dependencies to latest versions.
  package-lock.json
  package.json
Labels: dependencies
